### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by coderSkyChen** [twjiang/graphSAGE-pytorch#12]
cmd: python -m src.main --epochs 50 --learn_method unsup

information:

DEVICE: cpu
GraphSage with Net Unsupervised Learning
----------------------EPOCH 0-----------------------
Step [1/68], Loss: 10.8708, Dealed Nodes [1024/1355] 
Traceback (most recent call last):
  File "/data/webdev/xiaokaichen/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/webdev/xiaokaichen/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/webdev/xiaokaichen/code/graphSAGE-pytorch/src/main.py", line 72, in <module>
    graphSage, classification = apply_model(dataCenter, ds, graphSage, classification, unsupervised_loss, args.b_sz, args.unsup_loss, device, args.learn_method)
  File "/data/webdev/xiaokaichen/code/graphSAGE-pytorch/src/utils.py", line 186, in apply_model
    nn.utils.clip_grad_norm_(model.parameters(), 5)
  File "/data/webdev/xiaokaichen/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/utils/clip_grad.py", line 30, in clip_grad_norm_
    total_norm = torch.norm(torch.stack([torch.norm(p.grad.detach(), norm_type) for p in parameters]), norm_type)
RuntimeError: stack expects a non-empty TensorList

**Comment by coderSkyChen** [comment]
resolved by use torch1.0 instead of 1.5
