### ISSUE TITLE
 Could not find a version that satisfies the requirement torch==1.0.1.post2

### ISSUE THREAD

**Issue by linbeijianbaoxia** [twjiang/graphSAGE-pytorch#26]
env: pyhton 3.6.8
PC: window 10
IS torch==1.0.1.post2 not available on Windows？
很抱歉，我的找不到torch==1.0.1.post2，尝试安装1.0.0、1.0.1、1.1.0都会报错
错误信息如下：
DEVICE: cpu
Traceback (most recent call last):
  File "C:/Users/14656/Desktop/Program/GNN/Github/graphSAGE-pytorch-master/src/main.py", line 46, in <module>
    config = pyhocon.ConfigFactory.parse_file(args.config)
  File "C:\Users\14656\miniconda3\envs\graphSAGE-pytorch-master\lib\site-packages\pyhocon\config_parser.py", line 102, in parse_file
    raise e
  File "C:\Users\14656\miniconda3\envs\graphSAGE-pytorch-master\lib\site-packages\pyhocon\config_parser.py", line 97, in parse_file
    with codecs.open(filename, 'r', encoding=encoding) as fd:
  File "C:\Users\14656\miniconda3\envs\graphSAGE-pytorch-master\lib\codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './src/experiments.conf'

**Comment by Yuhao-Luo** [comment]
终端路径不对，你去看experiments.conf写法

**Comment by Mariyaaaaaaaaaa** [comment]
可以把main.py放在graphSAGE-pytorch-master下而不是src文件夹下。
